//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WPhast.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_PROPERTY_TREE               102
#define IDD_SCALE_PROPPAGE              102
#define IDD_PROPS_CUBE                  103
#define ID_NEW_ZONE                     105
#define ID_ZONE_TYPE_MEDIA              106
#define IDD_GRID_PROPPAGE_OLD           106
#define IDD_MEDIA_PROPPAGE              107
#define ID_ZONE_TYPE_BC_FLUX            107
#define IDD_NEW_ZONE_PROPPAGE           108
#define ID_ZONE_TYPE_BC_LEAKY           108
#define ID_ZONE_TYPE_BC_SPECIFIED       109
#define IDD_BC_FLUX_PROPPAGE            109
#define ID_ZONE_TYPE_IC_HEAD            110
#define IDD_TEST_PROPPAGE_LARGE         110
#define ID_ZONE_TYPE_6                  111
#define IDD_PROTO_PROPPAGE              111
#define ID_ZONE_TYPE_7                  112
#define IDD_PROTO2_PROPPAGE             112
#define ID_ZONE_TYPE_8                  113
#define IDD_PROTO3_PROPPAGE             113
#define ID_ZONE_TYPE_9                  114
#define IDD_BC_LEAKY_PROPPAGE           114
#define ID_ZONE_TYPE_10                 115
#define IDD_BC_SPECIFIED_PROPPAGE       115
#define ID_ZONE_TYPE_11                 116
#define ID_ZONE_TYPE_12                 117
#define ID_ZONE_TYPE_13                 118
#define ID_ZONE_TYPE_14                 119
#define ID_ZONE_TYPE_15                 120
#define IDR_HTML_IMPORTERRORDIALOG      121
#define IDR_HTML_UNITS1PROPERTYPAGE     122
#define ID_ZONE_TYPE_IC_CHEM            123
#define IDD_CHILDPROPERTYPAGE           125
#define IDR_MAINFRAME                   128
#define IDR_WPhastTYPE                  129
#define IDR_MEDIA_LONG_DISP_RTF         129
#define ID_VIEW_RESETDEFAULTLAYOUT      130
#define ID_INDICATOR_XYZ                131
#define IDR_MAINFRAME_SDI               132
#define ID_TOOLS_GEOMETRY               133
#define IDR_MENU1                       133
#define IDS_STRING133                   133
#define IDS_IMPORT_PHAST_TRANS_133      133
#define ID_TOOLS_NEWZONE                134
#define IDC_PAN_REAL                    135
#define IDS_MEDIA_PROPS_WIZ_135         135
#define IDC_NULL                        136
#define IDS_STRING136                   136
#define IDS_EXPORT_PHAST_TRANS_136      136
#define IDB_CHECKS                      137
#define IDS_UNITS1_CAPTION_137          137
#define IDB_CHECKS_TREE                 138
#define IDS_UNITS1_TITLE_138            138
#define IDS_UNITS1_SUBTITLE_139         139
#define IDS_UNITS2_CAPTION_140          140
#define IDS_UNITS2_TITLE_141            141
#define IDR_RTF1                        142
#define IDR_MEDIA_KX_RTF                142
#define IDS_UNITS2_SUBTITLE_142         142
#define IDR_MEDIA_ACTIVE_RTF            143
#define IDS_GRID_CAPTION_143            143
#define IDR_MEDIA_KY_RTF                144
#define IDS_GRID_TITLE_144              144
#define IDR_MEDIA_KZ_RTF                145
#define IDS_GRID_SUBTITLE_145           145
#define IDR_MEDIA_POROSITY_RTF          146
#define IDS_MEDIA_CAPTION_146           146
#define IDS_MEDIA_TITLE_147             147
#define IDR_MEDIA_SPEC_STORAGE_RTF      148
#define IDS_MEDIA_SUBTITLE_148          148
#define IDR_MEDIA_TRANS_DISP_RTF        149
#define IDS_IC_HEAD_CAPTION_149         149
#define IDR_BC_FLUX_ASSOC_SOL_RTF       150
#define IDS_IC_HEAD_TITLE_150           150
#define IDR_BC_FLUX_FLUX_RTF            151
#define IDS_IC_HEAD_SUBTITLE_151        151
#define IDR_BC_LEAKY_HEAD_RTF           152
#define IDS_TC_CAPTION_152              152
#define IDR_BC_LEAKY_THICKNESS_RTF      153
#define IDS_TC_TITLE_153                153
#define IDR_BC_LEAKY_HYD_COND_RTF       154
#define IDS_TC_SUBTITLE_154             154
#define IDR_BC_LEAKY_ASSOC_SOL_RTF      155
#define IDS_IMPMAP_CAPTION_155          155
#define IDR_BC_SPECIFIED_HEAD_RTF       156
#define IDS_IMPMAP_TITLE_156            156
#define IDR_BC_SPECIFIED_SOL_RTF        157
#define IDS_IMPMAP_SUBTITLE_157         157
#define IDD_INTRO                       158
#define IDS_CHEM_IC_CAPTION_158         158
#define IDB_BANNER                      159
#define IDS_CHEM_IC_TITLE_159           159
#define IDB_WATERMARK                   160
#define IDS_CHEM_IC_SUBTITLE_160        160
#define IDD_END                         161
#define IDS_CHEM_IC_CAPTION161          161
#define IDD_INTERIOR1                   162
#define IDD_INTERIOR2                   163
#define ID_FILE_EXPORT                  163
#define IDD_MEDIA2_PROPPAGE             164
#define ID_FILE_IMPORT                  164
#define IDD_MEDIA_EXT_PROPPAGE          164
#define IDD_BC_FLUX_PROPPAGE2           165
#define IDD_BC_SPECIFIED_PROPPAGE2      166
#define IDD_IMPORT_ERROR_DIALOG         167
#define IDD_UNITS1_PROPPAGE             168
#define IDD_UNITS_OLD                   169
#define IDR_IC_HEAD_MASK_RTF            169
#define IDD_UNITS2_PROPPAGE_OLD         170
#define IDR_IC_HEAD_HEAD_RTF            170
#define IDD_BC_LEAKY_PROPPAGE2          171
#define ID_FILE_RUN                     171
#define IDD_UNITS1_PROPPAGE_OLD         172
#define IDR_TC_TIME_STEP_RTF            172
#define IDD_UNITS2_PROPPAGE             173
#define IDR_TC_TIME_CHANGE_RTF          173
#define IDD_GRID_PROPPAGE               174
#define IDD_MEDIA_INT_PROPPAGE          175
#define IDD_IC_HEAD_INT_PROPPAGE        176
#define IDD_IC_HEAD_EXT_PROPPAGE        177
#define IDR_LONG_TOOLBAR                177
#define IDS_MDS_STEP1_177               177
#define IDS_MDS_POINT1_177              177
#define IDD_NEW_MODEL_INTRO             178
#define IDS_MDS_STEP2_178               178
#define IDS_MDS_POINT2_178              178
#define IDB_EYES_TREE                   178
#define IDD_TIME                        179
#define IDD_TC_INT_PROPPAGE             179
#define IDS_MDS_STEP3_179               179
#define IDS_MDS_GRID_179                179
#define IDB_EYES_TREE2                  179
#define IDD_RUN_OUTPUT_DIALOG           180
#define IDS_MDS_STEP1_SUB_180           180
#define IDS_MDS_POINT1_SUB_180          180
#define IDB_EYES_TREE3                  180
#define IDD_TC_INT_M_PROPPAGE           181
#define IDS_MDS_STEP2_SUB_181           181
#define IDS_MDS_POINT2_SUB_181          181
#define IDD_TC_INT_PROPPAGE1            182
#define IDS_MDS_STEP3_SUB_182           182
#define IDS_MDS_GRID_SUB_182            182
#define ID_VIEW_FROM_PX                 183
#define ID_VIEW_FROM_NX                 184
#define ID_VIEW_FROM_PY                 185
#define ID_VIEW_FROM_NY                 186
#define ID_VIEW_FROM_PZ                 187
#define ID_VIEW_FROM_NZ                 188
#define ID_VIEW_FROM_NEXT_DIRECTION     189
#define IDD_TEST_VTK                    190
#define IDD_MAP_DIALOG                  191
#define IDR_MAP_DIALOG_MENU             191
#define ID_VIEW_AXES                    192
#define IDD_AXES_PROPPAGE               192
#define ID_Menu                         193
#define IDD_MAP_PROPPAGE                193
#define ID_VIEW_SETPROJECTIONTO         194
#define IDD_IMPORT_MAP_PROPPAGE         194
#define ID_SETPROJECTIONTO_PERSPECTIVE  195
#define ID_SETPROJECTIONTO_PARALLEL     196
#define IDC_ZOOM_REAL                   198
#define IDC_SCALE_OBJ                   199
#define IDC_PIXEL_PICKER                204
#define IDD_COOR_DIALOG                 205
#define ID_VIEW_SITEMAP                 206
#define IDD_NEW_MODEL_INTRO1            206
#define IDD_NEW_MODEL_INTRO2            206
#define IDD_MODEL_OPTIONS               207
#define IDR_MEDIA_ALPHA_HORZ_RTF        207
#define IDR_MEDIA_ALPHA_VERT_RTF        208
#define IDD_CHEM_IC_INT_PROPPAGE        208
#define IDR_CHEM_IC_SOLUTION_RTF        209
#define IDD_FLOW_ONLY_INT_PROPPAGE      209
#define IDR_CHEM_IC_EQUILIBRIUM_PHASES_RTF 210
#define IDD_STEADY_FLOW_INT_PROPPAGE    210
#define IDR_CHEM_IC_SURFACE_RTF         211
#define IDD_FREE_SURFACE_INT_PROPPAGE   211
#define IDR_CHEM_IC_EXCHANGE_RTF        212
#define IDD_PRINT_FREQUENCY_EXT_PROPPAGE 212
#define IDR_CHEM_IC_GAS_PHASE_RTF       213
#define IDR_CHEM_IC_SOLID_SOLUTIONS_RTF 214
#define IDR_CHEM_IC_KINETICS_RTF        215
#define IDD_STARTUP_INTRO               216
#define IDD_FLOW_ONLY_INT_PROPPAGE2     217
#define ID_VIEW_GRID                    217
#define ID_VIEW_MEDIA                   218
#define IDD_PROPS_CUBE2                 218
#define ID_MEDIAZONES_ALL               219
#define IDD_WELL_PROPPAGE               219
#define ID_MEDIAZONES_SHOWSELECTED      220
#define IDD_WELL_PROPPAGE1              220
#define ID_MEDIAZONES_HIDEALL           221
#define IDD_WELL_PROPPAGE2              221
#define ID_MEDIAZONES_SHOWALL           222
#define IDD_BC_SPECIFIED_PROPPAGE3      222
#define IDD_BC_SPECIFIED_HEAD_PROPPAGE  222
#define ID_MEDIAZONES_RESETALLON        223
#define IDD_TEST_CMODGRIDCTRLEX         223
#define ID_MEDIAZONES_RESETALLOFF       224
#define IDD_BC_FLUX_PROPPAGE3           224
#define ID_MEDIAZONES_SETALLSELECTED    225
#define IDD_BC_LEAKY_PROPPAGE3          225
#define ID_MEDIAZONES_SETALLOFF         226
#define IDD_TC_INT_M_PROPPAGE2          226
#define ID_MEDIAZONES_SELECTALL         227
#define IDD_MEDIASPREAD_EXT_PROPPAGE    227
#define ID_MEDIAZONES_UNSELECTALL       228
#define IDD_CHEMICSPREAD_PROPPAGE       228
#define ID_VIEW_BCZONES                 229
#define IDD_IC_HEAD_SPREAD_PROPPAGE     229
#define ID_VIEW_ICZONES                 230
#define ID_BCZONES_HIDEALL              231
#define IDD_RIVER_PROPPAGE2             231
#define ID_BCZONES_SHOWSELECTED         232
#define IDD_RIVER_PROPPAGE              232
#define ID_BCZONES_SELECTALL            233
#define IDD_RIVERPT_PROPPAGE            233
#define ID_BCZONES_UNSELECTALL          234
#define IDD_RIVER_PROPPAGE3             234
#define ID_ICZONES_HIDEALL              235
#define IDD_RIVER_PROPPAGE4             235
#define ID_ICZONES_SHOWSELECTED         236
#define IDD_GRID_PROPPAGE2              236
#define ID_ICZONES_SELECTALL            237
#define IDD_GRID_PROPPAGE3              237
#define ID_ICZONES_UNSELECTALL          238
#define IDD_GRID_PROPPAGE4              238
#define ID_TOOLS_NEWSTRESSPERIOD        239
#define ID_TOOLS_NEWWELL                240
#define ID_WELLS_HIDEALL                241
#define ID_WELLS_SHOWSELECTED           242
#define ID_WELLS_SELECTALL              243
#define ID_WELLS_UNSELECTALL            244
#define IDD_SERIES_DIALOG               248
#define IDC_VE_SPLIT                    249
#define IDC_HO_SPLIT                    250
#define IDC_4WAY_02                     251
#define IDC_4WAY02                      251
#define IDC_EDIT_X                      1000
#define IDC_PROPERTIES                  1000
#define IDC_TITLE                       1000
#define IDC_EDIT_Y                      1001
#define IDC_INTRO_TEXT                  1001
#define IDC_EDIT_Z                      1002
#define IDC_SINGLE_VALUE_RADIO          1002
#define IDC_RADIO1                      1002
#define IDC_EDIT_Y2                     1002
#define IDC_EDIT_LENGTH                 1003
#define IDC_LINEAR_INTERPOLATION_RADIO  1003
#define IDC_RADIO2                      1003
#define IDC_EDIT_WIDTH                  1004
#define IDC_X_RADIO                     1004
#define IDC_YMAX_EDIT                   1004
#define IDC_RADIO3                      1004
#define IDC_LINE                        1004
#define IDC_EDIT_HEIGHT                 1005
#define IDC_Y_RADIO                     1005
#define IDC_ZMAX_EDIT                   1005
#define IDC_RADIO4                      1005
#define IDC_TUBE                        1005
#define IDC_EDIT_DEPTH                  1005
#define IDC_Z_RADIO                     1006
#define IDC_EDIT2                       1006
#define IDC_RADIO5                      1006
#define IDC_AXES_SIZE                   1006
#define IDC_SINGLE_VALUE_EDIT           1007
#define IDC_EDIT3                       1007
#define IDC_RADIO6                      1007
#define IDC_Z_ORIGIN                    1007
#define IDC_DISTANCE1_EDIT              1008
#define IDC_EDIT4                       1008
#define IDC_RADIO7                      1008
#define IDC_AXES_TUBE_DIAMETER          1008
#define IDC_VALUE1_EDIT                 1009
#define IDC_RADIO8                      1009
#define IDC_Y_ORIGIN                    1009
#define IDC_EDIT5                       1009
#define IDC_DISTANCE2_EDIT              1010
#define IDC_RADIO9                      1010
#define IDC_X_ORIGIN                    1010
#define IDC_EDIT6                       1010
#define IDC_VALUE2_EDIT                 1011
#define IDC_GROUP1                      1011
#define IDC_RADIO10                     1011
#define IDC_FACE_X_RADIO                1012
#define IDC_RADIO11                     1012
#define IDC_RICHEDIT22                  1013
#define IDC_RADIO12                     1013
#define IDC_EDIT7                       1013
#define IDC_X_EDIT                      1013
#define IDC_SINGLE_VALUE_STATIC         1014
#define IDC_RADIO13                     1014
#define IDC_EDIT8                       1014
#define IDC_Y_EDIT                      1014
#define IDC_DISTANCE1_STATIC            1015
#define IDC_VALUE1_STATIC               1016
#define IDC_DISTANCE2_STATIC            1017
#define IDC_RADIO14                     1017
#define IDC_VALUE2_STATIC               1018
#define IDC_FACE_Y_RADIO                1019
#define IDC_FACE_Z_RADIO                1020
#define IDC_CHECK1                      1021
#define IDC_CHECK2                      1022
#define IDC_CHECK3                      1023
#define IDC_XMIN_EDIT                   1024
#define IDC_YMIN_EDIT                   1025
#define IDC_ZMIN_EDIT                   1026
#define IDC_XSCALE                      1026
#define IDC_COMBO1                      1026
#define IDC_YSCALE                      1027
#define IDC_ZSCALE                      1028
#define IDC_XMAX_EDIT                   1029
#define IDC_BUTTON2                     1029
#define IDC_APPLY                       1030
#define IDC_TREE_ZONES                  1031
#define IDC_FACE_STATIC                 1032
#define IDC_PROP_TREE                   1034
#define IDC_PROP_LIST                   1036
#define IDC_LIST1                       1037
#define IDC_TREE1                       1038
#define IDC_LIST2                       1039
#define IDC_EXPLORER1                   1045
#define IDC_ASSOC_RADIO                 1047
#define IDC_FIXED_RADIO                 1048
#define IDC_SOL_TYPE_STATIC             1049
#define IDC_DESC_RICHEDIT               1050
#define IDC_LENGTH_STATIC               1054
#define IDC_FLOW_ONLY                   1057
#define IDC_ERRORS_RICHEDIT             1059
#define IDC_RADIO15                     1063
#define IDC_RADIO16                     1064
#define IDC_EDIT_HEIGHT_UNITS           1065
#define IDC_EDIT_WIDTH_UNITS            1066
#define IDC_STATIC_DIRECTION            1066
#define IDC_EDIT_LENGTH_UNITS           1067
#define IDC_EDIT_X_UNITS                1068
#define IDC_EDIT_Y_UNITS                1069
#define IDC_EDIT_Z_UNITS                1070
#define IDC_COMBO11                     1074
#define IDC_TIME_COMBO                  1075
#define IDC_HORZ_COMBO                  1076
#define IDC_VERT_COMBO                  1077
#define IDC_HEAD_COMBO                  1078
#define IDC_HYD_COND_NUM_COMBO          1079
#define IDC_HYD_COND_DENOM_COMBO        1080
#define IDC_STORAGE_DENOM_COMBO         1081
#define IDC_DISP_COMBO                  1082
#define IDC_FLUX_NUM_COMBO              1083
#define IDC_FLUX_DENOM_COMBO            1084
#define IDC_LEAKY_COND_NUM_COMBO        1085
#define IDC_LEAKY_COND_DENOM_COMBO      1086
#define IDC_LEAKY_THICK_COMBO           1087
#define IDC_WELL_DIAM_COMBO             1088
#define IDC_WELL_FLOW_NUM_COMBO         1089
#define IDC_WELL_FLOW_DENOM_COMBO       1090
#define IDC_RIVER_COND_NUM_COMBO        1091
#define IDC_RIVER_COND_DENOM_COMBO      1092
#define IDC_RIVER_THICK_COMBO           1093
#define IDC_XMIN_UNITS_STATIC           1094
#define IDC_XMAX_UNITS_STATIC           1095
#define IDC_YMIN_UNITS_STATIC           1096
#define IDC_MOL_DIFF_EDIT               1096
#define IDC_STATIC_SNAP_UNITS           1096
#define IDC_ZMIN_UNITS_STATIC           1097
#define IDC_FLOW_ONLY_RADIO             1097
#define IDC_YMAX_UNITS_STATIC           1098
#define IDC_SOLUTE_TRANSPORT_RADIO      1098
#define IDC_ZMAX_UNITS_STATIC           1099
#define IDC_MOL_DIFF_STATIC             1099
#define IDC_TIME_STEP_EDIT              1100
#define IDC_TIME_STEP_COMBO             1101
#define IDC_TIME_CHANGE_COMBO           1102
#define IDC_TIME_CHANGE_EDIT            1103
#define IDC_TIME_CHANGE_STATIC          1104
#define IDC_TIME_STEP_STATIC            1105
#define IDC_ABORT                       1106
#define IDC_TC_LIST                     1107
#define IDC_NEW_BUTTON                  1108
#define IDC_EDIT_BUTTON                 1109
#define IDC_DELETE_BUTTON               1110
#define IDC_CUSTOM1                     1112
#define IDC_GRID                        1112
#define IDC_BOTTOM                      1113
#define IDC_GRID_SCHEDULES              1113
#define IDC_SOLUTION_GRID               1113
#define IDC_SINGLE_GRID                 1114
#define IDC_EDIT_MO_X                   1115
#define IDC_STATIC_MODEL_ORIGIN         1116
#define IDC_EDIT_MO_Y                   1119
#define IDC_STATIC_MO_ANGLE             1120
#define IDC_EDIT_MO_ANGLE               1121
#define IDC_STATIC_XY                   1122
#define IDC_STATIC_MO_GB                1124
#define IDC_STATIC_LENGTH               1126
#define IDC_STATIC_WIDTH                1127
#define IDC_STATIC_GD                   1128
#define IDC_EDIT1                       1129
#define IDC_STATIC_DEPTH                1129
#define IDC_WORLD_EDIT                  1130
#define IDC_EDIT_START                  1130
#define IDC_STATIC_Y2                   1131
#define IDC_STATIC_YC3                  1131
#define IDC_EDIT_YC3                    1132
#define IDC_EDIT_WXP2                   1133
#define IDC_BROWSE_MAP_BUTTON           1134
#define IDC_EDIT_WYP2                   1134
#define IDC_BROWSE_WORLD_BUTTON         1135
#define IDC_EDIT_WXC2                   1135
#define IDC_IMPORT_NO                   1136
#define IDC_EDIT_WYC2                   1136
#define IDC_IMPORT_YES                  1137
#define IDC_MAP_EDIT                    1138
#define IDC_USE_WORLD_CHECK             1139
#define IDC_X_NODES_STATIC              1141
#define IDC_Y_NODES_STATIC              1142
#define IDC_Z_NODES_STATIC              1143
#define IDC_X_NODES_EDIT                1144
#define IDC_Y_NODES_EDIT                1145
#define IDC_X_NODES_EDIT2               1145
#define IDC_Z_NODES_EDIT                1146
#define IDC_X_SPIN                      1147
#define IDC_Y_SPIN                      1148
#define IDC_X_SPIN2                     1148
#define IDC_Z_SPIN                      1149
#define IDC_STATIC_X                    1150
#define IDC_STATIC_Y                    1151
#define IDC_STATIC_Z                    1152
#define IDC_STATIC_MO_X                 1153
#define IDC_STATIC_MO_Y                 1154
#define IDC_STATIC_MO_Z                 1155
#define IDC_STATIC_P1_GB                1156
#define IDC_STATIC_XP1                  1157
#define IDC_EDIT_XP1                    1158
#define IDC_SPIN_XP1                    1159
#define IDC_STATIC_YP1                  1160
#define IDC_EDIT_YP1                    1161
#define IDC_SPIN_YP1                    1162
#define IDC_STATIC_XC1                  1163
#define IDC_EDIT_XC1                    1164
#define IDC_STATIC_YC1                  1165
#define IDC_EDIT_YC1                    1166
#define IDC_STATIC_P2_GB                1167
#define IDC_STATIC_XP2                  1168
#define IDC_EDIT_XP2                    1169
#define IDC_SPIN_XP2                    1170
#define IDC_STATIC_YP2                  1171
#define IDC_EDIT_YP2                    1172
#define IDC_SPIN_YP2                    1173
#define IDC_STATIC_XC2                  1174
#define IDC_EDIT_XC2                    1175
#define IDC_STATIC_YC2                  1176
#define IDC_EDIT_YC2                    1177
#define IDC_STATIC_WORLD_GB             1178
#define IDC_STATIC_WXP                  1179
#define IDC_EDIT_WXP                    1180
#define IDC_STATIC_WYP                  1181
#define IDC_EDIT_WYP                    1182
#define IDC_STATIC_WXC                  1183
#define IDC_EDIT_WXC                    1184
#define IDC_STATIC_WYC                  1185
#define IDC_EDIT_WYC                    1186
#define IDC_BUTTON1                     1187
#define IDC_BACK_BUTTON                 1188
#define IDC_BUTTON_INSERT               1188
#define IDC_BUTTON3                     1188
#define IDC_MODIFY_CHECK                1189
#define IDC_BUTTON_DELETE               1189
#define IDC_BUTTON4                     1189
#define IDC_STEADY_FLOW_RADIO           1191
#define IDC_TRANSIENT_FLOW_RADIO        1192
#define IDC_CONFINED_FLOW_RADIO         1193
#define IDC_FREE_SURFACE_RADIO          1194
#define IDC_OPEN_FILE                   1195
#define IDC_NEW_WIZARD                  1196
#define IDC_EDIT_XMIN                   1197
#define IDC_EDIT_YMIN                   1198
#define IDC_EDIT_ZMIN                   1199
#define IDC_EDIT_XMAX                   1200
#define IDC_EDIT_YMAX                   1201
#define IDC_EDIT_ZMAX                   1202
#define IDC_GRID_SCREENS                1203
#define IDC_X_UNITS_STATIC              1204
#define IDC_Y_UNITS_STATIC              1205
#define IDC_LSD_UNITS_STATIC            1206
#define IDC_BY_DEPTH_CHECK              1207
#define IDC_LSD_STATIC                  1208
#define IDC_LSD_EDIT                    1209
#define IDC_LSD_UNITS_STATIC2           1210
#define IDC_LSD_EDIT3                   1211
#define IDC_LSD_EDIT2                   1212
#define IDC_LSD_UNITS_STATIC3           1213
#define IDC_LSD_STATIC2                 1214
#define IDC_LSD_EDIT4                   1215
#define IDC_DIAM_EDIT                   1215
#define IDC_DIAMETER_UNITS_STATIC       1216
#define IDC_ELEVATION_RADIO             1217
#define IDC_DIAMETER_UNITS_STATIC3      1217
#define IDC_DEPTH_RADIO                 1218
#define IDC_DIAMETER_UNITS_STATIC4      1218
#define IDC_DIAM_RADIO                  1219
#define IDC_WIDTH_EDIT                  1219
#define IDC_RADIUS_RADIO                1220
#define IDC_DIAMETER_UNITS_STATIC2      1220
#define IDC_WELL_STATIC                 1221
#define IDC_NUSER_EDIT                  1222
#define IDC_DESC_EDIT                   1223
#define IDC_ALLOCATE_BY_HEAD            1224
#define IDC_HEAD_GRID                   1225
#define IDC_FLUX_GRID                   1229
#define IDC_TIMESTEP_GRID               1230
#define IDC_TIMEEND_GRID                1231
#define IDC_BUTTON_ADD                  1232
#define IDC_CHECK_SAVE_HEADS            1233
#define IDC_MEDIA_GRID                  1234
#define IDC_CHEMIC_GRID                 1235
#define IDC_HEADIC_GRID                 1236
#define IDC_DEPTH_EDIT                  1237
#define IDC_DEPTH_EDIT2                 1238
#define IDC_RIVER_PTS                   1238
#define IDC_DEPTH_EDIT3                 1239
#define IDC_DEPTH_UNITS_STATIC          1240
#define IDC_WIDTH_UNITS_STATIC          1241
#define IDC_RIVER_K_UNITS_STATIC        1242
#define IDC_RIVER_THICK_UNITS_STATIC    1243
#define IDC_RIVER_K_UNITS_EDIT          1244
#define IDC_RIVER_THICK_UNITS_EDIT      1245
#define IDC_BOTTOM_UNITS_STATIC         1245
#define IDC_RIVER_K_EDIT                1246
#define IDC_RIVER_THICK_EDIT            1247
#define IDC_RADIO_BOTTOM                1248
#define IDC_BOTTOM_EDIT                 1249
#define IDC_RADIO_DEPTH                 1250
#define IDC_TAB_COOR                    1251
#define IDC_GRID_NONUNIFORM             1253
#define IDC_RADIO_UNIFORM               1254
#define IDC_RADIO_NONUNIFORM            1255
#define IDC_STATIC_MIN                  1256
#define IDC_EDIT_MIN                    1257
#define IDC_STATIC_MIN_UNITS            1258
#define IDC_STATIC_MAX_UNITS            1259
#define IDC_STATIC_MAX                  1260
#define IDC_STATIC_U_NODES              1261
#define IDC_STATIC_N_NODES              1262
#define IDC_EDIT_MAX                    1263
#define IDC_EDIT_U_NODES                1264
#define IDC_SPIN_U_NODES                1265
#define IDC_SPIN_N_NODES                1266
#define IDC_EDIT_SNAP                   1267
#define IDC_EDIT_N_NODES                1268
#define IDC_BUTTON_INS                  1269
#define IDC_BUTTON_DEL                  1270
#define IDC_BUTTON_SERIES               1271
#define IDC_RADIO_XY                    1272
#define IDC_RADIO_XZ                    1273
#define IDC_CHECK_X                     1274
#define IDC_CHECK_Y                     1275
#define IDC_CHECK_Z                     1276
#define IDC_EDIT_STEP                   1277
#define IDC_EDIT_STOP                   1278
#define IDC_RADIO_LINEAR                1279
#define IDC_RADIO_GROWTH                1280
#define IDC_RESIZE_COLUMN               28654
#define IDC_RESIZE_ROW                  28655
#define IDR_POPUP                       28656
#define ID_NEW_CUBE                     32773
#define ID_TOOLS_NEWRIVER               32793
#define ID_BUTTON32795                  32795
#define ID_TOOLS_MOVE_VER_LINE          32801
#define IDW_CONTROLBAR_TREE             59424
#define IDW_CONTROLBAR_BOXPROPS         59425

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        252
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1281
#define _APS_NEXT_SYMED_VALUE           126
#endif
#endif
