//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by obsolete.rc
//
#define IDD_GRID_PROPPAGE_OLD           106
#define IDD_MEDIA_PROPPAGE              107
#define IDD_BC_FLUX_PROPPAGE            109
#define IDD_PROTO_PROPPAGE              111
#define IDD_PROTO2_PROPPAGE             112
#define IDD_PROTO3_PROPPAGE             113
#define IDD_BC_LEAKY_PROPPAGE           114
#define IDD_BC_SPECIFIED_PROPPAGE       115
#define IDD_BC_FLUX_PROPPAGE2           165
#define IDD_BC_SPECIFIED_PROPPAGE2      166
#define IDD_UNITS_OLD                   169
#define IDD_UNITS2_PROPPAGE_OLD         170
#define IDD_BC_LEAKY_PROPPAGE2          171
#define IDD_UNITS1_PROPPAGE_OLD         172
#define IDD_TC_INT_PROPPAGE             179
#define IDD_TC_INT_PROPPAGE1            182
#define IDD_CHEM_IC_INT_PROPPAGE        208
#define IDD_WELL_PROPPAGE               219
#define IDD_WELL_PROPPAGE2              221
#define IDD_RIVER_PROPPAGE2             231
#define IDD_RIVER_PROPPAGE              232
#define IDD_RIVER_PROPPAGE3             234
#define IDD_GRID_PROPPAGE2              236
#define IDD_GRID_PROPPAGE3              237
#define IDD_PRINT_INITIAL_PROPPAGE      253
#define IDD_TC_INT_PROPPAGE2            254
#define IDC_SINGLE_VALUE_RADIO          1002
#define IDC_RADIO1                      1002
#define IDC_LINEAR_INTERPOLATION_RADIO  1003
#define IDC_RADIO2                      1003
#define IDC_X_RADIO                     1004
#define IDC_YMAX_EDIT                   1004
#define IDC_RADIO3                      1004
#define IDC_Y_RADIO                     1005
#define IDC_ZMAX_EDIT                   1005
#define IDC_RADIO4                      1005
#define IDC_Z_RADIO                     1006
#define IDC_RADIO5                      1006
#define IDC_EDIT2                       1006
#define IDC_SINGLE_VALUE_EDIT           1007
#define IDC_RADIO6                      1007
#define IDC_DISTANCE1_EDIT              1008
#define IDC_RADIO7                      1008
#define IDC_VALUE1_EDIT                 1009
#define IDC_RADIO8                      1009
#define IDC_EDIT5                       1009
#define IDC_DISTANCE2_EDIT              1010
#define IDC_RADIO9                      1010
#define IDC_EDIT6                       1010
#define IDC_VALUE2_EDIT                 1011
#define IDC_RADIO10                     1011
#define IDC_RADIO11                     1012
#define IDC_RICHEDIT22                  1013
#define IDC_X_EDIT                      1013
#define IDC_RADIO12                     1013
#define IDC_SINGLE_VALUE_STATIC         1014
#define IDC_Y_EDIT                      1014
#define IDC_RADIO13                     1014
#define IDC_DISTANCE1_STATIC            1015
#define IDC_VALUE1_STATIC               1016
#define IDC_DISTANCE2_STATIC            1017
#define IDC_RADIO14                     1017
#define IDC_VALUE2_STATIC               1018
#define IDC_CHECK1                      1021
#define IDC_CHECK2                      1022
#define IDC_CHECK3                      1023
#define IDC_XMIN_EDIT                   1024
#define IDC_YMIN_EDIT                   1025
#define IDC_ZMIN_EDIT                   1026
#define IDC_XMAX_EDIT                   1029
#define IDC_FACE_STATIC                 1032
#define IDC_PROP_TREE                   1034
#define IDC_PROP_LIST                   1036
#define IDC_LIST2                       1039
#define IDC_ASSOC_RADIO                 1047
#define IDC_FIXED_RADIO                 1048
#define IDC_SOL_TYPE_STATIC             1049
#define IDC_DESC_RICHEDIT               1050
#define IDC_FLOW_ONLY                   1057
#define IDC_RADIO15                     1063
#define IDC_RADIO16                     1064
#define IDC_STATIC_DIRECTION            1066
#define IDC_TIME_COMBO                  1075
#define IDC_HORZ_COMBO                  1076
#define IDC_VERT_COMBO                  1077
#define IDC_HEAD_COMBO                  1078
#define IDC_HYD_COND_NUM_COMBO          1079
#define IDC_HYD_COND_DENOM_COMBO        1080
#define IDC_STORAGE_DENOM_COMBO         1081
#define IDC_DISP_COMBO                  1082
#define IDC_FLUX_NUM_COMBO              1083
#define IDC_FLUX_DENOM_COMBO            1084
#define IDC_LEAKY_COND_NUM_COMBO        1085
#define IDC_LEAKY_COND_DENOM_COMBO      1086
#define IDC_LEAKY_THICK_COMBO           1087
#define IDC_WELL_DIAM_COMBO             1088
#define IDC_WELL_FLOW_NUM_COMBO         1089
#define IDC_WELL_FLOW_DENOM_COMBO       1090
#define IDC_RIVER_COND_NUM_COMBO        1091
#define IDC_RIVER_COND_DENOM_COMBO      1092
#define IDC_RIVER_THICK_COMBO           1093
#define IDC_XMIN_UNITS_STATIC           1094
#define IDC_XMAX_UNITS_STATIC           1095
#define IDC_TIME_STEP_EDIT              1100
#define IDC_TIME_STEP_COMBO             1101
#define IDC_TIME_CHANGE_COMBO           1102
#define IDC_TIME_CHANGE_EDIT            1103
#define IDC_TIME_CHANGE_STATIC          1104
#define IDC_TIME_STEP_STATIC            1105
#define IDC_GRID                        1112
#define IDC_GRID_SCHEDULES              1113
#define IDC_EDIT1                       1129
#define IDC_X_NODES_EDIT                1144
#define IDC_Y_NODES_EDIT                1145
#define IDC_X_NODES_EDIT2               1145
#define IDC_Z_NODES_EDIT                1146
#define IDC_X_SPIN                      1147
#define IDC_Y_SPIN                      1148
#define IDC_X_SPIN2                     1148
#define IDC_Z_SPIN                      1149
#define IDC_BUTTON1                     1187
#define IDC_BUTTON3                     1188
#define IDC_BUTTON4                     1189
#define IDC_GRID_SCREENS                1203
#define IDC_X_UNITS_STATIC              1204
#define IDC_Y_UNITS_STATIC              1205
#define IDC_LSD_UNITS_STATIC            1206
#define IDC_BY_DEPTH_CHECK              1207
#define IDC_LSD_STATIC                  1208
#define IDC_LSD_EDIT                    1209
#define IDC_LSD_UNITS_STATIC2           1210
#define IDC_LSD_EDIT2                   1212
#define IDC_DIAM_EDIT                   1215
#define IDC_DIAMETER_UNITS_STATIC       1216
#define IDC_DIAMETER_UNITS_STATIC3      1217
#define IDC_ELEVATION_RADIO             1217
#define IDC_DIAMETER_UNITS_STATIC4      1218
#define IDC_DEPTH_RADIO                 1218
#define IDC_WIDTH_EDIT                  1219
#define IDC_DIAM_RADIO                  1219
#define IDC_DIAMETER_UNITS_STATIC2      1220
#define IDC_RADIUS_RADIO                1220
#define IDC_WELL_STATIC                 1221
#define IDC_NUSER_EDIT                  1222
#define IDC_DESC_EDIT                   1223
#define IDC_ALLOCATE_BY_HEAD            1224
#define IDC_MEDIA_GRID                  1234
#define IDC_DEPTH_EDIT                  1237
#define IDC_DEPTH_EDIT2                 1238
#define IDC_RIVER_PTS                   1238
#define IDC_DEPTH_EDIT3                 1239
#define IDC_DEPTH_UNITS_STATIC          1240
#define IDC_WIDTH_UNITS_STATIC          1241
#define IDC_RIVER_K_UNITS_STATIC        1242
#define IDC_RIVER_THICK_UNITS_STATIC    1243
#define IDC_BOTTOM_UNITS_STATIC         1245
#define IDC_RIVER_K_EDIT                1246
#define IDC_RIVER_THICK_EDIT            1247
#define IDC_RADIO_BOTTOM                1248
#define IDC_BOTTOM_EDIT                 1249
#define IDC_RADIO_DEPTH                 1250
#define IDC_TAB_COOR                    1251
#define IDC_FACE_X_RADIO                1343
#define IDC_FACE_Y_RADIO                1344
#define IDC_FACE_Z_RADIO                1345

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
