//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WPhast.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_PROPERTY_TREE               102
#define IDD_SCALE_PROPPAGE              102
#define IDD_PROPS_CUBE                  103
#define ID_NEW_ZONE                     105
#define ID_ZONE_TYPE_MEDIA              106
#define ID_ZONE_TYPE_BC_FLUX            107
#define IDD_NEW_ZONE_PROPPAGE           108
#define ID_ZONE_TYPE_BC_LEAKY           108
#define ID_ZONE_TYPE_BC_SPECIFIED       109
#define ID_ZONE_TYPE_IC_HEAD            110
#define IDD_TEST_PROPPAGE_LARGE         110
#define ID_ZONE_TYPE_FLOW_RATE          111
#define ID_ZONE_TYPE_7                  112
#define ID_ZONE_TYPE_8                  113
#define ID_ZONE_TYPE_9                  114
#define ID_ZONE_TYPE_10                 115
#define ID_ZONE_TYPE_11                 116
#define ID_ZONE_TYPE_12                 117
#define ID_ZONE_TYPE_13                 118
#define ID_ZONE_TYPE_14                 119
#define ID_ZONE_TYPE_15                 120
#define IDR_HTML_IMPORTERRORDIALOG      121
#define IDR_HTML_UNITS1PROPERTYPAGE     122
#define ID_ZONE_TYPE_IC_CHEM            123
#define IDD_CHILDPROPERTYPAGE           125
#define IDD_PROPS_PAGE                  126
#define IDR_MAINFRAME                   128
#define IDR_WPhastTYPE                  129
#define IDR_MEDIA_LONG_DISP_RTF         129
#define ID_VIEW_RESETDEFAULTLAYOUT      130
#define ID_INDICATOR_XYZ                131
#define IDR_MAINFRAME_SDI               132
#define ID_TOOLS_GEOMETRY               133
#define IDR_MENU1                       133
#define IDS_STRING133                   133
#define IDS_IMPORT_PHAST_TRANS_133      133
#define IDR_MAINFRAME_SDI1              133
#define IDR_GRID_ACCEL                  133
#define ID_TOOLS_NEWZONE                134
#define IDC_PAN_REAL                    135
#define IDS_MEDIA_PROPS_WIZ_135         135
#define IDC_NULL                        136
#define IDS_STRING136                   136
#define IDS_EXPORT_PHAST_TRANS_136      136
#define IDB_CHECKS                      137
#define IDS_UNITS1_CAPTION_137          137
#define IDB_CHECKS_TREE                 138
#define IDS_UNITS1_TITLE_138            138
#define IDS_UNITS1_SUBTITLE_139         139
#define IDS_UNITS2_CAPTION_140          140
#define IDS_UNITS2_TITLE_141            141
#define IDR_RTF1                        142
#define IDR_MEDIA_KX_RTF                142
#define IDS_UNITS2_SUBTITLE_142         142
#define IDR_MEDIA_ACTIVE_RTF            143
#define IDS_GRID_CAPTION_143            143
#define IDR_MEDIA_KY_RTF                144
#define IDS_GRID_TITLE_144              144
#define IDR_MEDIA_KZ_RTF                145
#define IDS_GRID_SUBTITLE_145           145
#define IDR_MEDIA_POROSITY_RTF          146
#define IDS_MEDIA_CAPTION_146           146
#define IDS_MEDIA_TITLE_147             147
#define IDR_MEDIA_SPEC_STORAGE_RTF      148
#define IDS_MEDIA_SUBTITLE_148          148
#define IDR_MEDIA_TRANS_DISP_RTF        149
#define IDS_IC_HEAD_CAPTION_149         149
#define IDR_BC_FLUX_ASSOC_SOL_RTF       150
#define IDS_IC_HEAD_TITLE_150           150
#define IDR_BC_FLUX_FLUX_RTF            151
#define IDS_IC_HEAD_SUBTITLE_151        151
#define IDR_BC_LEAKY_HEAD_RTF           152
#define IDS_TC_CAPTION_152              152
#define IDR_BC_LEAKY_THICKNESS_RTF      153
#define IDS_TC_TITLE_153                153
#define IDR_BC_LEAKY_HYD_COND_RTF       154
#define IDS_TC_SUBTITLE_154             154
#define IDR_BC_LEAKY_ASSOC_SOL_RTF      155
#define IDS_IMPMAP_CAPTION_155          155
#define IDR_BC_SPECIFIED_HEAD_RTF       156
#define IDS_IMPMAP_TITLE_156            156
#define IDR_BC_SPECIFIED_SOL_RTF        157
#define IDS_IMPMAP_SUBTITLE_157         157
#define IDD_INTRO                       158
#define IDS_CHEM_IC_CAPTION_158         158
#define IDB_BANNER                      159
#define IDS_CHEM_IC_TITLE_159           159
#define IDB_WATERMARK                   160
#define IDS_CHEM_IC_SUBTITLE_160        160
#define IDD_END                         161
#define IDS_CHEM_IC_CAPTION161          161
#define IDD_INTERIOR1                   162
#define IDS_GREATER_THAN_ZERO           162
#define IDD_INTERIOR2                   163
#define ID_FILE_EXPORT                  163
#define IDD_MEDIA2_PROPPAGE             164
#define ID_FILE_IMPORT                  164
#define IDD_MEDIA_EXT_PROPPAGE          164
#define IDS_UNITS3_CAPTION_164          164
#define IDS_UNITS3_TITLE_165            165
#define IDS_UNITS3_SUBTITLE_166         166
#define IDD_IMPORT_ERROR_DIALOG         167
#define IDS_UNITS4_CAPTION_167          167
#define OLD_UNITS1_PROPPAGE             168
#define IDS_UNITS4_TITLE_168            168
#define IDR_IC_HEAD_MASK_RTF            169
#define IDS_UNITS4_SUBTITLE_169         169
#define IDR_IC_HEAD_HEAD_RTF            170
#define ID_FILE_RUN                     171
#define IDR_TC_TIME_STEP_RTF            172
#define OLD_UNITS2_PROPPAGE             173
#define IDR_TC_TIME_CHANGE_RTF          173
#define IDD_GRID_PROPPAGE               174
#define IDD_MEDIA_INT_PROPPAGE          175
#define IDD_IC_HEAD_INT_PROPPAGE        176
#define IDR_LONG_TOOLBAR                177
#define IDS_MDS_STEP1_177               177
#define IDS_MDS_POINT1_177              177
#define IDD_IC_HEAD_EXT_PROPPAGE        177
#define IDD_NEW_MODEL_INTRO             178
#define IDS_MDS_STEP2_178               178
#define IDS_MDS_POINT2_178              178
#define IDB_EYES_TREE                   178
#define IDD_TIME                        179
#define IDS_MDS_STEP3_179               179
#define IDS_MDS_GRID_179                179
#define IDB_EYES_TREE2                  179
#define IDD_TC_INT_PROPPAGE             179
#define IDD_RUN_OUTPUT_DIALOG           180
#define IDS_MDS_STEP1_SUB_180           180
#define IDS_MDS_POINT1_SUB_180          180
#define IDB_EYES_TREE3                  180
#define IDS_MDS_STEP2_SUB_181           181
#define IDS_MDS_POINT2_SUB_181          181
#define IDD_TC_INT_M_PROPPAGE           181
#define IDR_MAINFRAME2                  181
#define IDS_MDS_STEP3_SUB_182           182
#define IDS_MDS_GRID_SUB_182            182
#define ID_VIEW_FROM_PX                 183
#define ID_VIEW_FROM_NX                 184
#define ID_VIEW_FROM_PY                 185
#define ID_VIEW_FROM_NY                 186
#define ID_VIEW_FROM_PZ                 187
#define ID_VIEW_FROM_NZ                 188
#define ID_VIEW_FROM_NEXT_DIRECTION     189
#define IDD_TEST_VTK                    190
#define IDD_MAP_DIALOG                  191
#define IDR_MAP_DIALOG_MENU             191
#define ID_VIEW_AXES                    192
#define IDD_AXES_PROPPAGE               192
#define ID_Menu                         193
#define IDD_MAP_PROPPAGE                193
#define ID_VIEW_SETPROJECTIONTO         194
#define IDD_IMPORT_MAP_PROPPAGE         194
#define ID_SETPROJECTIONTO_PERSPECTIVE  195
#define ID_SETPROJECTIONTO_PARALLEL     196
#define IDC_ZOOM_REAL                   198
#define IDC_SCALE_OBJ                   199
#define IDC_PIXEL_PICKER                204
#define IDD_COOR_DIALOG                 205
#define ID_VIEW_SITEMAP                 206
#define IDD_NEW_MODEL_INTRO1            206
#define IDD_NEW_MODEL_INTRO2            206
#define IDD_MODEL_OPTIONS               207
#define IDR_MEDIA_ALPHA_HORZ_RTF        207
#define IDR_MEDIA_ALPHA_VERT_RTF        208
#define IDR_CHEM_IC_SOLUTION_RTF        209
#define IDD_FLOW_ONLY_INT_PROPPAGE      209
#define IDR_CHEM_IC_EQUILIBRIUM_PHASES_RTF 210
#define IDD_STEADY_FLOW_INT_PROPPAGE    210
#define IDR_CHEM_IC_SURFACE_RTF         211
#define IDD_FREE_SURFACE_INT_PROPPAGE   211
#define IDR_CHEM_IC_EXCHANGE_RTF        212
#define IDD_PRINT_FREQUENCY_EXT_PROPPAGE 212
#define IDR_CHEM_IC_GAS_PHASE_RTF       213
#define IDR_CHEM_IC_SOLID_SOLUTIONS_RTF 214
#define IDR_CHEM_IC_KINETICS_RTF        215
#define IDD_STARTUP_INTRO               216
#define IDD_FLOW_ONLY_INT_PROPPAGE2     217
#define ID_VIEW_GRID                    217
#define ID_VIEW_MEDIA                   218
#define IDD_PROPS_CUBE2                 218
#define ID_MEDIAZONES_ALL               219
#define ID_MEDIAZONES_SHOWSELECTED      220
#define IDD_WELL_PROPPAGE1              220
#define ID_MEDIAZONES_HIDEALL           221
#define ID_MEDIAZONES_SHOWALL           222
#define IDD_BC_SPECIFIED_PROPPAGE3      222
#define IDD_BC_SPECIFIED_HEAD_PROPPAGE  222
#define ID_MEDIAZONES_RESETALLON        223
#define IDD_TEST_CMODGRIDCTRLEX         223
#define ID_MEDIAZONES_RESETALLOFF       224
#define IDD_BC_FLUX_PROPPAGE3           224
#define ID_MEDIAZONES_SETALLSELECTED    225
#define IDD_BC_LEAKY_PROPPAGE3          225
#define ID_MEDIAZONES_SETALLOFF         226
#define IDD_TC_INT_M_PROPPAGE2          226
#define ID_MEDIAZONES_SELECTALL         227
#define IDD_MEDIASPREAD_EXT_PROPPAGE    227
#define ID_MEDIAZONES_UNSELECTALL       228
#define IDD_CHEMICSPREAD_PROPPAGE       228
#define ID_VIEW_BCZONES                 229
#define IDD_IC_HEAD_SPREAD_PROPPAGE     229
#define ID_VIEW_ICZONES                 230
#define ID_BCZONES_HIDEALL              231
#define ID_BCZONES_SHOWSELECTED         232
#define ID_BCZONES_SELECTALL            233
#define IDD_RIVERPT_PROPPAGE            233
#define ID_BCZONES_UNSELECTALL          234
#define ID_ICZONES_HIDEALL              235
#define IDD_RIVER_PROPPAGE4             235
#define ID_ICZONES_SHOWSELECTED         236
#define ID_ICZONES_SELECTALL            237
#define ID_ICZONES_UNSELECTALL          238
#define IDD_GRID_PROPPAGE4              238
#define ID_TOOLS_NEWSTRESSPERIOD        239
#define ID_TOOLS_NEWWELL                240
#define ID_WELLS_HIDEALL                241
#define ID_INDICATOR_GRID               241
#define ID_WELLS_SHOWSELECTED           242
#define ID_INDICATOR_MAP                242
#define ID_WELLS_SELECTALL              243
#define ID_INDICATOR_SPACE              243
#define ID_WELLS_UNSELECTALL            244
#define IDS_UNITS5_CAPTION_244          244
#define IDS_UNITS5_TITLE_245            245
#define IDS_UNITS5_SUBTITLE_246         246
#define IDD_SERIES_DIALOG               248
#define IDC_VE_SPLIT                    249
#define IDD_GRID_REFINE                 249
#define IDC_HO_SPLIT                    250
#define IDD_GRID_COARSEN                250
#define IDC_4WAY02                      251
#define IDD_SOLUTION_METHOD_PROPPAGE    251
#define IDB_PLUS_MERGE                  252
#define IDD_PRINT_INITIAL_EXT_PROPPAGE  252
#define IDD_SERIES_DIALOG2              254
#define IDC_3DGARROW                    255
#define IDR_WELL_RATE_RTF               256
#define IDR_WELL_SOLUTION_RTF           257
#define IDR_WELL_TIME_RTF               258
#define IDR_WELL_UNITS_RTF              259
#define IDR_STEADY_FLOW_RTF             260
#define IDR_TRANSIENT_RTF               261
#define IDR_HEAD_TOLERANCE_RTF          262
#define IDR_FLOW_BALANCE_TOLERANCE_RTF  263
#define IDR_MINIMUM_TIME_STEP_RTF       264
#define IDR_MAXIMUM_TIME_STEP_RTF       265
#define IDR_HEAD_CHANGE_TARGET_RTF      266
#define IDR_ITERATIONS_RTF              267
#define IDD_SUBDIVIDE_DIALOG            273
#define IDD_BC_TYPE_DIALOG              275
#define IDD_COLORS                      276
#define IDD_PROPS_RIVER                 278
#define IDR_DESCRIPTION_RTF             279
#define IDD_PROPS_CUBE3                 279
#define IDR_SOLUTE_TRUE_RTF             280
#define IDD_PROPS_WEDGE                 280
#define IDR_SOLUTE_FALSE_RTF            281
#define IDD_PROPS_PRISM                 281
#define IDR_DIFFUSIVITY_RTF             282
#define IDD_PROPS_WELL                  282
#define IDR_FREE_SURFACE_TRUE_RTF       283
#define IDD_PROPS_PRISM2                283
#define IDR_FREE_SURFACE_FALSE_RTF      284
#define IDD_PROPS_CUBE4                 284
#define IDR_SM_ITERATIVE_TRUE_RTF       285
#define IDR_SM_ITERATIVE_FALSE_RTF      286
#define IDR_SM_TOLERANCE_RTF            287
#define IDR_SM_SAVE_DIR_RTF             288
#define IDR_SM_MAX_ITER_RTF             289
#define IDR_SM_SPACE_RTF                290
#define IDR_SM_TIME_DIFF_RTF            291
#define IDR_SM_CROSS_DISP_RTF           292
#define IDR_SM_REBALANCE_RTF            293
#define IDR_GRID_UNI_RTF                294
#define IDR_GRID_NONUNI_RTF             295
#define IDR_GRID_MIN_RTF                296
#define IDR_GRID_MAX_RTF                297
#define IDR_GRID_NODES_RTF              298
#define IDR_GRID_SNAP_RTF               299
#define IDR_GRID_ORIENT_RTF             300
#define IDR_GRID_CHEM_DIMS_RTF          301
#define IDR_BC_LEAKY_FACE_RTF           302
#define IDR_BC_FLUX_FACE_RTF            303
#define IDR_BC_SOL_TYPE_RTF             304
#define IDR_BC_SPECIFIED_SOL_FIX_RTF    305
#define IDR_BC_SPECIFIED_SOL_ASSOC_RTF  306
#define IDR_WELL_ALLOCATE_RTF           307
#define IDR_WELL_DEPTH_RTF              308
#define IDR_WELL_DESC_RTF               309
#define IDR_WELL_DIAM_RTF               310
#define IDR_WELL_ELEVATION_RTF          311
#define IDR_WELL_LOCATION_RTF           312
#define IDR_WELL_LSD_RTF                313
#define IDR_WELL_NUMBER_RTF             314
#define IDR_WELL_RADIUS_RTF             315
#define IDR_RIVER_NUM_RTF               316
#define IDR_RIVER_DESC_RTF              317
#define IDR_RIVER_LOC_RTF               318
#define IDR_RIVER_WIDTH_RTF             319
#define IDR_RIVER_HYD_COND_RTF          320
#define IDR_RIVER_THICK_RTF             321
#define IDR_RIVER_DEPTH_RTF             322
#define IDR_RIVER_BOTTOM_RTF            323
#define IDR_RIVER_START_RTF             324
#define IDR_RIVER_UNITS_RTF             325
#define IDR_RIVER_HEAD_RTF              326
#define IDR_RIVER_SOLUTION_RTF          327
#define IDR_PR_INIT_BC_RTF              328
#define IDR_PR_INIT_COMPS_RTF           329
#define IDR_PR_INIT_ECHO_RTF            330
#define IDR_PR_INIT_FLUID_RTF           331
#define IDR_PR_INIT_FORCE_RTF           332
#define IDR_PR_INIT_HDF_CHEM_RTF        333
#define IDR_PR_INIT_HDF_HEAD_RTF        334
#define IDR_PR_INIT_HDF_VEL_RTF         335
#define IDR_PR_INIT_HEADS_RTF           336
#define IDR_PR_INIT_MEDIA_RTF           337
#define IDR_PR_INIT_SOL_METH_RTF        338
#define IDR_PR_INIT_SSFLOW_RTF          339
#define IDR_PR_INIT_WELLS_RTF           340
#define IDR_PR_INIT_XYZ_CHEM_RTF        341
#define IDR_PR_INIT_XYZ_COMPS_RTF       342
#define IDR_PR_INIT_XYZ_HEADS_RTF       343
#define IDR_PR_INIT_XYZ_SSVEL_RTF       344
#define IDR_PR_INIT_XYZ_WELLS_RTF       345
#define IDR_PR_INIT_COND_RTF            346
#define IDR_PR_FREQ_FR_BC_RTF           364
#define IDR_PR_FREQ_COMPS_RTF           365
#define IDR_PR_FREQ_COND_RTF            366
#define IDR_PR_FREQ_FLOW_BAL_RTF        367
#define IDR_PR_FREQ_FORCE_RTF           368
#define IDR_PR_FREQ_HDF_CHEM_RTF        369
#define IDR_PR_FREQ_HDF_HEAD_RTF        370
#define IDR_PR_FREQ_HDF_VEL_RTF         371
#define IDR_PR_FREQ_PROG_RTF            372
#define IDR_PR_FREQ_VEL_RTF             373
#define IDR_PR_FREQ_WELLS_RTF           374
#define IDR_PR_FREQ_XYZ_CHEM_RTF        375
#define IDR_PR_FREQ_XYZ_COMPS_RTF       376
#define IDR_PR_FREQ_XYZ_HEADS_RTF       377
#define IDR_PR_FREQ_XYZ_VEL_RTF         378
#define IDR_PR_FREQ_XYZ_WELLS_RTF       379
#define IDR_PR_FREQ_BC_RTF              380
#define IDR_PR_FREQ_HEADS_RTF           381
#define IDR_PR_FREQ_SAVE_HEADS_RTF      382
#define IDR_PR_FREQ_TIME_RTF            383
#define IDR_TC_TS_TIME_RTF              384
#define IDR_TC_TS_UNITS_RTF             385
#define IDR_TC_TS_TIME_STEP_RTF         386
#define IDR_TC_TS_TIME_STEP_UNITS_RTF   387
#define IDR_TC_TE_TIME_END_RTF          388
#define IDR_TC_TE_TIME_END_UNITS_RTF    389
#define IDR_SM_REBALANCE_BY_CELL_RTF    390
#define IDD_DIALOG_PERIMETER            393
#define IDD_DRAIN_PROPPAGE              394
#define IDD_UNITS1_PROPPAGE             395
#define IDD_UNITS2_PROPPAGE             396
#define IDD_UNITS3_PROPPAGE             397
#define IDD_UNITS4_PROPPAGE             398
#define IDD_WELL_PROPPAGE2              399
#define IDD_PROPS_WEDGE1                400
#define IDD_PROPS_WEDGE2                401
#define IDD_FLOW_RATE_PROPPAGE          402
#define IDD_PROP_PROPPAGE               403
#define IDD_PROP_PROPPAGE1              404
#define IDR_TOOLBAR1                    404
#define IDD_PROP_PROPPAGE2              405
#define IDR_MAINFRAME3                  405
#define IDD_PROP_PROPPAGE3              406
#define IDR_MAINFRAME4                  406
#define IDR_MAINFRAME2_24BIT            406
#define IDD_PROP_PROPPAGE4              407
#define IDD_PROP_PROPPAGE5              408
#define IDD_PROP_CONSTANT               409
#define IDD_PROPS_MEDIA                 410
#define IDD_PROP_NONE                   411
#define IDD_PROP_LINEAR                 412
#define IDD_PROP_POINTS                 413
#define IDD_PROP_XYZ                    414
#define IDD_PROP_CONSTANT_M             416
#define IDD_PROP_DESC                   417
#define IDD_PROPS_HEADIC                418
#define IDD_PROPS_ICCHEM                419
#define IDD_PROPS_MEDIA1                420
#define IDD_PROP_RICH                   421
#define IDD_PROPS_FLUX                  422
#define IDD_PROP_LINEAR_M               423
#define IDD_PROP_NONE_M                 424
#define IDD_PROPS_FLUX_2                425
#define IDD_DIALOG1                     426
#define IDD_DIALOG2                     427
#define IDD_DIALOG3                     428
#define IDD_DIALOG4                     429
#define IDD_PROPS_SPECIFIED_HEAD        430
#define IDD_PROPS_MIXTURE               432
#define IDD_PROPS_LEAKY                 433
#define IDD_PROPS_TIMESERIES            434
#define IDD_PROPS_SPECIFIED_HEAD2       435
#define IDD_PROPS_FLUX_3                436
#define IDD_PROPS_MEDIA2                437
#define IDD_PROPS_HEADIC2               438
#define IDD_PROPS_ICCHEM2               439
#define IDD_FLOW_RATE_PROPPAGE2         440
#define IDD_NEW_ZONE_PROPPAGE2          441
#define IDS_IMPORT_PHAST_TRANS_442      442
#define IDD_UNITS5_PROPPAGE             442
#define IDD_PROPS_ZONEPROPS             443
#define ID_INDICATOR_COOR               443
#define IDD_PROPS_ZONEPROPS1            444
#define IDC_EDIT_X                      1000
#define IDC_TITLE                       1000
#define IDC_EDIT_Y                      1001
#define IDC_INTRO_TEXT                  1001
#define IDC_EDIT_Z                      1002
#define IDC_RADIO1                      1002
#define IDC_EDIT_Y2                     1002
#define IDC_RADIO_MAP                   1003
#define IDC_XY_GRID_RADIO               1008
#define IDC_SINGLE_VALUE_RADIO          1009
#define IDC_EDIT_WIDTH                  1010
#define IDC_EDIT_LENGTH                 1011
#define IDC_EDIT_DEPTH                  1012
#define IDC_RADIO2                      1013
#define IDC_LINEAR_INTERPOLATION_RADIO  1014
#define IDC_XY_MAP_RADIO                1015
#define IDC_LINEAR_INTERPOLATION_RADIO2 1015
#define IDC_RADIO3                      1016
#define IDC_LINEAR_INTERPOLATION_RADIO3 1016
#define IDC_LINE                        1017
#define IDC_LINEAR_INTERPOLATION_RADIO4 1017
#define IDC_YMAX_EDIT                   1018
#define IDC_X_RADIO                     1019
#define IDC_RADIO4                      1020
#define IDC_X_RADIO2                    1020
#define IDC_TUBE                        1021
#define IDC_EDIT_HEIGHT                 1022
#define IDC_ZMAX_EDIT                   1023
#define IDC_Y_RADIO                     1024
#define IDC_EDIT2                       1025
#define IDC_Y_RADIO2                    1025
#define IDC_RADIO5                      1026
#define IDC_AXES_SIZE                   1027
#define IDC_Z_RADIO                     1028
#define IDC_EDIT3                       1029
#define IDC_Z_RADIO2                    1029
#define IDC_RADIO6                      1030
#define IDC_Z_ORIGIN                    1031
#define IDC_SINGLE_VALUE_EDIT           1032
#define IDC_EDIT4                       1033
#define IDC_RADIO7                      1034
#define IDC_AXES_TUBE_DIAMETER          1035
#define IDC_DISTANCE1_EDIT              1036
#define IDC_VALUE1_EDIT                 1037
#define IDC_RADIO8                      1038
#define IDC_VALUE1_EDIT2                1038
#define IDC_Y_ORIGIN                    1039
#define IDC_DISTANCE1_EDIT2             1039
#define IDC_X_ORIGIN                    1040
#define IDC_DISTANCE2_EDIT              1041
#define IDC_VALUE2_EDIT                 1042
#define IDC_GROUP1                      1043
#define IDC_VALUE2_EDIT2                1043
#define IDC_EDIT7                       1044
#define IDC_DISTANCE2_EDIT2             1044
#define IDC_X_EDIT                      1045
#define IDC_EDIT8                       1046
#define IDC_Y_EDIT                      1047
#define IDC_SINGLE_VALUE_STATIC         1048
#define IDC_DISTANCE1_STATIC            1049
#define IDC_VALUE1_STATIC               1050
#define IDC_DISTANCE2_STATIC            1051
#define IDC_VALUE2_STATIC               1052
#define IDC_CHECK1                      1053
#define IDC_VALUE1_STATIC2              1053
#define IDC_XMIN_EDIT                   1054
#define IDC_CHECK2                      1054
#define IDC_DISTANCE1_STATIC2           1054
#define IDC_YMIN_EDIT                   1055
#define IDC_CHECK3                      1055
#define IDC_VALUE2_STATIC2              1055
#define IDC_XSCALE                      1056
#define IDC_CHECK4                      1056
#define IDC_DISTANCE2_STATIC2           1056
#define IDC_COMBO1                      1057
#define IDC_ZMIN_EDIT                   1058
#define IDC_YSCALE                      1059
#define IDC_ZSCALE                      1060
#define IDC_BUTTON2                     1061
#define IDC_XMAX_EDIT                   1062
#define IDC_APPLY                       1063
#define IDC_BUTTON3                     1064
#define IDC_TREE_ZONES                  1065
#define IDC_FACE_STATIC                 1066
#define IDC_PROP_TREE                   1067
#define IDC_LIST1                       1068
#define IDC_PROP_TREE2                  1068
#define IDC_TREE1                       1069
#define IDC_LIST2                       1070
#define IDC_EXPLORER1                   1071
#define IDC_ASSOC_RADIO                 1072
#define IDC_FIXED_RADIO                 1073
#define IDC_SOL_TYPE_STATIC             1074
#define IDC_DESC_RICHEDIT               1075
#define IDC_LENGTH_STATIC               1076
#define IDC_ERRORS_RICHEDIT             1077
#define IDC_EDIT_HEIGHT_UNITS           1078
#define IDC_EDIT_WIDTH_UNITS            1079
#define IDC_STATIC_DIRECTION            1080
#define IDC_EDIT_LENGTH_UNITS           1081
#define IDC_STATIC_DIRECTION2           1081
#define IDC_EDIT_X_UNITS                1082
#define IDC_EDIT_Y_UNITS                1083
#define IDC_EDIT_Z_UNITS                1084
#define IDC_COMBO11                     1085
#define IDC_TIME_COMBO                  1086
#define IDC_HORZ_COMBO                  1087
#define IDC_VERT_COMBO                  1088
#define IDC_HEAD_COMBO                  1089
#define IDC_HYD_COND_NUM_COMBO          1090
#define IDC_HORZ_MAP_COMBO              1091
#define IDC_HYD_COND_DENOM_COMBO        1092
#define IDC_VERT_MAP_COMBO              1093
#define IDC_STORAGE_DENOM_COMBO         1094
#define IDC_DISP_COMBO                  1095
#define IDC_FLUX_NUM_COMBO              1096
#define IDC_FLUX_DENOM_COMBO            1097
#define IDC_LEAKY_COND_NUM_COMBO        1098
#define IDC_LEAKY_COND_DENOM_COMBO      1099
#define IDC_LEAKY_THICK_COMBO           1100
#define IDC_WELL_DIAM_COMBO             1101
#define IDC_WELL_FLOW_NUM_COMBO         1102
#define IDC_WELL_FLOW_DENOM_COMBO       1103
#define IDC_RIVER_COND_NUM_COMBO        1104
#define IDC_RIVER_COND_DENOM_COMBO      1105
#define IDC_RIVER_THICK_COMBO           1106
#define IDC_WELL_DEPTH_COMBO            1107
#define IDC_XMIN_UNITS_STATIC           1108
#define IDC_RIVER_WIDTH_COMBO           1109
#define IDC_XMAX_UNITS_STATIC           1110
#define IDC_RIVER_WIDTH_COMBO2          1111
#define IDC_RIVER_DEPTH_COMBO           1112
#define IDC_DRAIN_COND_NUM_COMBO        1113
#define IDC_MOL_DIFF_EDIT               1114
#define IDC_STATIC_SNAP_UNITS           1115
#define IDC_YMIN_UNITS_STATIC           1116
#define IDC_DRAIN_COND_DENOM_COMBO      1117
#define IDC_FLOW_ONLY_RADIO             1118
#define IDC_ZMIN_UNITS_STATIC           1119
#define IDC_DRAIN_THICK_COMBO           1120
#define IDC_SOLUTE_TRANSPORT_RADIO      1121
#define IDC_YMAX_UNITS_STATIC           1122
#define IDC_DRAIN_WIDTH_COMBO           1123
#define IDC_MOL_DIFF_STATIC             1124
#define IDC_ZMAX_UNITS_STATIC           1125
#define IDC_TIME_STEP_EDIT              1126
#define IDC_TIME_STEP_COMBO             1127
#define IDC_TIME_CHANGE_COMBO           1128
#define IDC_TIME_CHANGE_EDIT            1129
#define IDC_TIME_CHANGE_STATIC          1130
#define IDC_TIME_STEP_STATIC            1131
#define IDC_ABORT                       1132
#define IDC_TC_LIST                     1133
#define IDC_NEW_BUTTON                  1134
#define IDC_EDIT_BUTTON                 1135
#define IDC_DELETE_BUTTON               1136
#define IDC_CUSTOM1                     1137
#define IDC_GRID                        1138
#define IDC_BOTTOM                      1139
#define IDC_GRID_SCHEDULES              1140
#define IDC_SOLUTION_GRID               1141
#define IDC_GRID_LEFT                   1142
#define IDC_SINGLE_GRID                 1143
#define IDC_EDIT_MO_X                   1144
#define IDC_STATIC_MODEL_ORIGIN         1145
#define IDC_EDIT_MO_Y                   1146
#define IDC_STATIC_MO_ANGLE             1147
#define IDC_EDIT_MO_ANGLE               1148
#define IDC_STATIC_XY                   1149
#define IDC_STATIC_MO_GB                1150
#define IDC_STATIC_LENGTH               1151
#define IDC_STATIC_WIDTH_XX             1151
#define IDC_STATIC_WIDTH                1152
#define IDC_STATIC_GD                   1153
#define IDC_STATIC_DEPTH                1154
#define IDC_WORLD_EDIT                  1155
#define IDC_EDIT_START                  1156
#define IDC_FACTOR_EDIT                 1157
#define IDC_STATIC_Y2                   1158
#define IDC_STATIC_YC3                  1159
#define IDC_EDIT_YC3                    1160
#define IDC_EDIT_WXP2                   1161
#define IDC_BROWSE_MAP_BUTTON           1162
#define IDC_EDIT_WYP2                   1163
#define IDC_BROWSE_WORLD_BUTTON         1164
#define IDC_EDIT_WXC2                   1165
#define IDC_IMPORT_NO                   1166
#define IDC_EDIT_WYC2                   1167
#define IDC_IMPORT_YES                  1168
#define IDC_MAP_EDIT                    1169
#define IDC_USE_WORLD_CHECK             1170
#define IDC_X_NODES_STATIC              1171
#define IDC_Y_NODES_STATIC              1172
#define IDC_Z_NODES_STATIC              1173
#define IDC_X_NODES_EDIT                1174
#define IDC_Y_NODES_EDIT                1175
#define IDC_Z_NODES_EDIT                1176
#define IDC_X_SPIN                      1177
#define IDC_Y_SPIN                      1178
#define IDC_Z_SPIN                      1179
#define IDC_STATIC_X                    1180
#define IDC_STATIC_Y                    1181
#define IDC_STATIC_Z                    1182
#define IDC_STATIC_MO_X                 1183
#define IDC_STATIC_MO_Y                 1184
#define IDC_STATIC_MO_Z                 1185
#define IDC_STATIC_P1_GB                1186
#define IDC_STATIC_XP1                  1187
#define IDC_EDIT_XP1                    1188
#define IDC_SPIN_XP1                    1189
#define IDC_STATIC_YP1                  1190
#define IDC_EDIT_YP1                    1191
#define IDC_SPIN_YP1                    1192
#define IDC_STATIC_XC1                  1193
#define IDC_EDIT_XC1                    1194
#define IDC_STATIC_YC1                  1195
#define IDC_EDIT_YC1                    1196
#define IDC_STATIC_P2_GB                1197
#define IDC_STATIC_XP2                  1198
#define IDC_EDIT_XP2                    1199
#define IDC_SPIN_XP2                    1200
#define IDC_STATIC_YP2                  1201
#define IDC_EDIT_YP2                    1202
#define IDC_SPIN_YP2                    1203
#define IDC_STATIC_XC2                  1204
#define IDC_EDIT_XC2                    1205
#define IDC_STATIC_YC2                  1206
#define IDC_EDIT_YC2                    1207
#define IDC_STATIC_WORLD_GB             1208
#define IDC_STATIC_WXP                  1209
#define IDC_EDIT_WXP                    1210
#define IDC_STATIC_WYP                  1211
#define IDC_EDIT_WYP                    1212
#define IDC_STATIC_WXC                  1213
#define IDC_EDIT_WXC                    1214
#define IDC_STATIC_WYC                  1215
#define IDC_EDIT_WYC                    1216
#define IDC_BUTTON1                     1217
#define IDC_BACK_BUTTON                 1218
#define IDC_BUTTON4                     1218
#define IDC_BUTTON_INSERT               1219
#define IDC_MODIFY_CHECK                1220
#define IDC_BUTTON_DELETE               1221
#define IDC_STEADY_FLOW_RADIO           1222
#define IDC_TRANSIENT_FLOW_RADIO        1223
#define IDC_CONFINED_FLOW_RADIO         1224
#define IDC_FREE_SURFACE_RADIO          1225
#define IDC_OPEN_FILE                   1226
#define IDC_NEW_WIZARD                  1227
#define IDC_EDIT_XMIN                   1228
#define IDC_NEW_WIZARD2                 1229
#define IDC_IMPORT_TRANS                1230
#define IDC_EDIT_YMIN                   1231
#define IDC_EDIT_ZMIN                   1232
#define IDC_EDIT_XMAX                   1233
#define IDC_EDIT_YMAX                   1234
#define IDC_EDIT_ZMAX                   1235
#define IDC_GRID_SCREENS                1236
#define IDC_X_UNITS_STATIC              1237
#define IDC_Y_UNITS_STATIC              1238
#define IDC_LSD_UNITS_STATIC            1239
#define IDC_X_UNITS_STATIC2             1240
#define IDC_Y_UNITS_STATIC2             1241
#define IDC_LSD_STATIC                  1242
#define IDC_Z_UNITS_STATIC2             1243
#define IDC_LSD_EDIT                    1244
#define IDC_LSD_EDIT3                   1245
#define IDC_LSD_UNITS_STATIC3           1246
#define IDC_LSD_STATIC2                 1247
#define IDC_LSD_EDIT4                   1248
#define IDC_DIAM_EDIT                   1249
#define IDC_DIAMETER_UNITS_STATIC       1250
#define IDC_ELEVATION_RADIO             1251
#define IDC_DEPTH_RADIO                 1252
#define IDC_DIAM_RADIO                  1253
#define IDC_WIDTH_EDIT                  1254
#define IDC_RADIUS_RADIO                1255
#define IDC_WELL_STATIC                 1256
#define IDC_NUSER_EDIT                  1257
#define IDC_DESC_EDIT                   1258
#define IDC_ALLOCATE_BY_HEAD            1259
#define IDC_HEAD_GRID                   1260
#define IDC_FLUX_GRID                   1261
#define IDC_TIMESTEP_GRID               1262
#define IDC_TIMEEND_GRID                1263
#define IDC_BUTTON_ADD                  1264
#define IDC_CHECK_SAVE_HEADS            1265
#define IDC_MEDIA_GRID                  1266
#define IDC_CHEMIC_GRID                 1267
#define IDC_HEADIC_GRID                 1268
#define IDC_DEPTH_EDIT                  1269
#define IDC_DEPTH_UNITS_STATIC          1270
#define IDC_WIDTH_UNITS_STATIC          1271
#define IDC_RIVER_K_UNITS_STATIC        1272
#define IDC_RIVER_THICK_UNITS_STATIC    1273
#define IDC_RIVER_K_UNITS_EDIT          1274
#define IDC_RIVER_THICK_UNITS_EDIT      1275
#define IDC_BOTTOM_UNITS_STATIC         1276
#define IDC_RIVER_K_EDIT                1277
#define IDC_RIVER_THICK_EDIT            1278
#define IDC_RADIO_BOTTOM                1279
#define IDC_BOTTOM_EDIT                 1280
#define IDC_RADIO_DEPTH                 1281
#define IDC_TAB_COOR                    1282
#define IDC_DRAIN_Z_EDIT                1283
#define IDC_GRID_NONUNIFORM             1284
#define IDC_RADIO_UNIFORM               1285
#define IDC_RADIO_NONUNIFORM            1286
#define IDC_STATIC_MIN                  1287
#define IDC_EDIT_MIN                    1288
#define IDC_STATIC_MIN_UNITS            1289
#define IDC_STATIC_MAX_UNITS            1290
#define IDC_STATIC_MAX                  1291
#define IDC_STATIC_U_NODES              1292
#define IDC_STATIC_SPACE                1293
#define IDC_STATIC_N_NODES              1294
#define IDC_STATIC_TIME                 1295
#define IDC_EDIT_MAX                    1296
#define IDC_EDIT_U_NODES                1297
#define IDC_EDIT_SPACE                  1298
#define IDC_SPIN_U_NODES                1299
#define IDC_EDIT_TIME                   1300
#define IDC_SPIN_N_NODES                1301
#define IDC_EDIT_MAX_I                  1302
#define IDC_STATIC_REBAL                1303
#define IDC_EDIT_SNAP                   1304
#define IDC_SPIN_MAX_I                  1305
#define IDC_EDIT_REBAL                  1306
#define IDC_EDIT_N_NODES                1307
#define IDC_EDIT_PARTS_I                1308
#define IDC_BUTTON_INS                  1309
#define IDC_SPIN_PARTS_I                1310
#define IDC_BUTTON_DEL                  1311
#define IDC_EDIT_MAX_J                  1312
#define IDC_BUTTON_SERIES               1313
#define IDC_SPIN_MAX_J                  1314
#define IDC_RADIO_XY                    1315
#define IDC_EDIT_PARTS_J                1316
#define IDC_RADIO_XZ                    1317
#define IDC_SPIN_PARTS_J                1318
#define IDC_CHECK_X                     1319
#define IDC_EDIT_MAX_K                  1320
#define IDC_CHECK_Y                     1321
#define IDC_SPIN_MAX_K                  1322
#define IDC_CHECK_Z                     1323
#define IDC_EDIT_PARTS_K                1324
#define IDC_EDIT_STEP                   1325
#define IDC_SPIN_PARTS_K                1326
#define IDC_BUTTON_SUBDIVIDE            1327
#define IDC_EDIT_STOP                   1328
#define IDC_RADIO_LINEAR                1329
#define IDC_RADIO_GROWTH                1330
#define IDC_EDIT_MIN_I                  1331
#define IDC_EDIT_END                    1332
#define IDC_SPIN_MIN_I                  1333
#define IDC_EDIT_MIN_J                  1334
#define IDC_SPIN_MIN_J                  1335
#define IDC_EDIT_MIN_K                  1336
#define IDC_SPIN_MIN_K                  1337
#define IDC_CHECK_Z2                    1338
#define IDC_CHECK_X2                    1339
#define IDC_CHECK_Y2                    1340
#define IDC_STATIC_SN_X                 1341
#define IDC_STATIC_SN_Y                 1342
#define IDC_STATIC_SN_Z                 1343
#define IDC_STATIC_EN_X                 1344
#define IDC_STATIC_EN_Y                 1345
#define IDC_STATIC_EN_Z                 1346
#define IDC_STATIC_SE_X                 1347
#define IDC_STATIC_SE_Y                 1348
#define IDC_STATIC_SE_Z                 1349
#define IDC_STATIC_E_X                  1350
#define IDC_STATIC_E_Y                  1351
#define IDC_STATIC_E_Z                  1352
#define IDC_STATIC_ME_X                 1353
#define IDC_STATIC_ME_Y                 1354
#define IDC_STATIC_ME_Z                 1355
#define IDC_STATIC_TOL                  1356
#define IDC_EDIT_TOL                    1357
#define IDC_STATIC_SAVE                 1358
#define IDC_EDIT_SAVE                   1359
#define IDC_SPIN_SAVE                   1360
#define IDC_SPIN_MAX                    1361
#define IDC_CHECK_CROSS_DISP            1362
#define IDC_RADIO_ITER                  1363
#define IDC_RADIO_DIRECT                1364
#define IDC_HEAD_TOL_STATIC             1365
#define IDC_CHECK_CROSS_DISP2           1366
#define IDC_CHECK_REBALANCE_BY_CELL     1367
#define IDC_HEAD_TOL_EDIT               1368
#define IDC_HEAD_TOL_UNITS_STATIC       1369
#define IDC_FB_TOL_STATIC               1370
#define IDC_FB_TOL_EDIT                 1371
#define IDC_MIN_TS_COMBO                1372
#define IDC_MIN_TS_STATIC               1373
#define IDC_MIN_TS_EDIT                 1374
#define IDC_MAX_TS_STATIC               1375
#define IDC_MAX_TS_EDIT                 1376
#define IDC_MAX_TS_COMBO                1377
#define IDC_HCT_STATIC                  1378
#define IDC_HCT_EDIT                    1379
#define IDC_ITER_EDIT                   1380
#define IDC_ITER_STATIC                 1381
#define IDC_ITER_SPIN                   1382
#define IDC_HCT_UNITS_STATIC            1383
#define IDC_HCT_CHECK                   1384
#define IDC_MAX_TS_CHECK                1385
#define IDC_MIN_TS_CHECK                1386
#define IDC_FACE_X_RADIO                1387
#define IDC_FACE_Y_RADIO                1388
#define IDC_FACE_Z_RADIO                1389
#define IDC_GRID_RIGHT                  1390
#define IDC_EDIT_INCR                   1391
#define IDC_EDIT_FACTOR                 1392
#define IDC_STATIC_FACTOR               1393
#define IDC_DESC_STATIC                 1394
#define IDC_SNAP_GB                     1395
#define IDC_UNIFORM_GB                  1396
#define IDC_NON_UNIFORM_GB              1397
#define IDC_PRINT_GB                    1398
#define IDC_CHEM_GB                     1399
#define IDC_SECTIONS_SPIN               1400
#define IDC_SECTIONS_EDIT               1401
#define IDC_MULT_DIV_COMBO              1402
#define IDC_START_EDIT                  1403
#define IDC_END_EDIT                    1404
#define IDC_INTERVAL_STATIC             1405
#define IDC_START_WIDTH_STATIC          1406
#define IDC_END_WIDTH_STATIC            1407
#define IDC_RADIO_LEAKY                 1408
#define IDC_RADIO_HEAD                  1409
#define IDC_RADIO_FLUX                  1410
#define IDC_MEDIA_BTN                   1411
#define IDC_FLUX_BTN                    1412
#define IDC_LEAKY_BTN                   1413
#define IDC_HEAD_IC_BTN                 1414
#define IDC_CHEM_IC_BTN                 1415
#define IDC_SPEC_HEAD_BTN               1416
#define IDC_RIVER_BTN                   1417
#define IDC_RIVER_BTN2                  1418
#define IDC_ZONE_FLOW_BTN               1418
#define IDC_WELL_BTN                    1419
#define IDC_STATIC_WELL_X               1420
#define IDC_WELL_BTN2                   1421
#define IDC_BG_BTN                      1422
#define IDC_STATIC_WELL_Y               1423
#define IDC_DRAIN_BTN                   1423
#define IDC_EDIT_WELL_X                 1424
#define IDC_ZONE_CURSOR_BTN             1424
#define IDC_EDIT_WELL_Y                 1425
#define IDC_STATIC_LOC                  1426
#define IDC_GRID_RIVER                  1427
#define IDC_UNITS_STATIC                1428
#define IDC_GRID_RIVER2                 1429
#define IDC_GRID_POINTS                 1430
#define IDC_STARTTIME_EDIT              1431
#define IDC_STARTTIME_STATIC            1432
#define IDC_STARTTIME_COMBO             1433
#define IDC_STATIC_MIN_WEDGE            1434
#define IDC_STATIC_MAX_WEDGE            1435
#define IDC_STATIC_X_WEDGE              1436
#define IDC_EDIT_XMIN_WEDGE             1437
#define IDC_EDIT_XMAX_WEDGE             1438
#define IDC_STATIC_Y_WEDGE              1439
#define IDC_EDIT_YMIN_WEDGE             1440
#define IDC_EDIT_YMAX_WEDGE             1441
#define IDC_STATIC_Z_WEDGE              1442
#define IDC_EDIT_ZMIN_WEDGE             1443
#define IDC_EDIT_ZMAX_WEDGE             1444
#define IDC_RADIO_X                     1445
#define IDC_RADIO_Y                     1446
#define IDC_RADIO_Z                     1447
#define IDC_RADIO_1                     1448
#define IDC_RADIO_2                     1449
#define IDC_RADIO_3                     1450
#define IDC_RADIO_4                     1451
#define IDC_X_UNITS_STATIC_WEDGE        1452
#define IDC_Y_UNITS_STATIC_WEDGE        1453
#define IDC_Z_UNITS_STATIC_WEDGE        1454
#define IDC_GB_AXIS                     1455
#define IDC_GB_CORNER                   1456
#define IDC_TAB                         1457
#define XXX_IDC_RADIO_NONE              1458
#define XXX_IDC_RADIO_CONSTANT          1459
#define XXX_IDC_RADIO_ARCRASTER         1460
#define XXX_IDC_RADIO_POINTS            1461
#define XXX_IDC_RADIO_SHAPE             1462
#define IDC_EDIT_CONSTANT               1463
#define IDC_EDIT_ARCRASTER              1464
#define IDC_EDIT_SHAPEFILE              1465
#define IDC_BUTTON_ARCRASTER            1466
#define IDC_BUTTON_SHAPE                1467
#define IDC_COMBO_SHAPE                 1468
#define IDC_RADIO_PERIM_DRAW            1469
#define IDC_RADIO_POINTS2               1469
#define XXX_IDC_RADIO_XYZ               1469
#define IDC_RADIO_PERIM_SHAPEFILE       1470
#define IDC_STATIC_CS_GB                1471
#define IDC_CHECK_USE_MAP               1472
#define IDC_CHECK_USE_MAP_Z             1473
#define IDC_CHECK_USE_MAP2              1474
#define IDC_CHECK_EXTERIOR_ONLY         1475
#define IDC_RADIO_EC_ALL                1476
#define IDC_RADIO_EC_X                  1477
#define IDC_RADIO_EC_Y                  1478
#define IDC_RADIO_EC_Z                  1479
#define IDC_GROWTH_STATIC               1480
#define IDC_GROWTH_EDIT                 1481
#define IDC_COMBINATION_LIST            1482
#define IDC_NUM_STATIC                  1483
#define IDC_NUM_EDIT                    1484
#define IDC_EDIT_LENGTH_XXX             1485
#define IDC_EDIT1                       1486
#define IDC_EDIT5                       1487
#define IDC_TREE_PROPS                  1488
#define IDC_TYPE_COMBO                  1489
#define IDC_DESC_PAGE                   1489
#define IDC_VALUE_EDIT                  1490
#define IDC_EDIT_XYZ                    1492
#define IDC_BUTTON_XYZ                  1493
#define IDC_TAB1                        1494
#define IDC_TIMES_GRID                  1495
#define IDC_GRID_SOLUTION               1496
#define IDC_RICH_PAGE                   1497
#define IDC_GB_PROPERTY                 1498
#define IDC_POINTS_GRID                 1499
#define IDC_GB_PROPERTY2                1499
#define IDC_USE_MAP_COOR                1500
#define IDC_STATIC_FN                   1501
#define IDC_GRID_HEAD                   1502
#define IDC_STATIC_PROPTYPE             1503
#define IDC_COMBO_PROPTYPE              1504
#define IDC_GB_PROPTYPE                 1505
#define IDC_CHECK_FACE                  1506
#define IDC_CHECK5                      1507
#define IDC_CHECK_MIXTURE               1507
#define IDC_GB_PROPTYPE2                1508
#define IDC_STATIC_PROPTYPE2            1509
#define IDC_COMBO_PROPTYPE2             1510
#define IDC_GB_MIXTURE                  1511
#define IDC_STATIC_I                    1512
#define IDC_STATIC_J                    1513
#define IDC_EDIT_J                      1514
#define IDC_EDIT_I                      1515
#define IDC_GRID_FLUX                   1516
#define IDC_STATIC_FACE                 1517
#define IDC_SU_PPASSEMBLAGE_COMBO       1518
#define IDC_SU_EXCHANGE_COMBO           1519
#define IDC_SU_SURFACE_COMBO            1520
#define IDC_SU_SSASSEMBLAGE_COMBO       1521
#define IDC_SU_KINETICS_COMBO           1522
#define IDC_SU_GASPHASE_COMBO           1523
#define IDC_RADIO_NONE                  1524
#define IDC_RADIO_CONSTANT              1525
#define IDC_RADIO_ARCRASTER             1526
#define IDC_RADIO_SHAPE                 1527
#define IDC_RADIO_XYZ                   1528
#define IDC_RADIO_POINTS                1529
#define IDC_BUTTON_ADD_POINT            1535
#define IDC_BUTTON_DELETE_POINT         1536
#define IDC_GB_COOR_SYS                 1537
#define IDC_RADIO_CS_GRID               1538
#define IDC_RADIO_CS_MAP                1539
#define IDC_RESIZE_COLUMN               28654
#define IDC_RESIZE_ROW                  28655
#define IDR_POPUP                       28656
#define ID_NEW_CUBE                     32773
#define ID_TOOLS_NEWRIVER               32793
#define ID_BUTTON32795                  32795
#define ID_TOOLS_MOVE_VER_LINE          32801
#define ID_TOOLS_MODIFYGRID             32805
#define ID_VIEW_HIDEALL                 32806
#define ID_RIVERS_HIDEALL               32807
#define ID_RIVERS_SHOWSELECTED          32808
#define ID_RIVERS_SELECTALL             32809
#define ID_RIVERS_UNSELECTALL           32810
#define ID_VIEW_FROM_PREV_DIRECTION     32812
#define ID_TOOLS_SELECTOBJECT           32826
#define ID_VIEW_SHOWALL                 32827
#define ID_TOOLS_COLORS                 32832
#define ID_VIEW_PROPERIESVIEW           32833
#define ID_VIEW_PROPERIESVIEW32834      32834
#define ID_VIEW_PROPERIESVIEW32835      32835
#define ID_EDIT_PROPERTIES              32837
#define ID_BUTTON32841                  32841
#define ID_TOOLS_NEWWEDGE               32841
#define ID_TOOLS_NEWPRISM               32842
#define ID_BUTTON32843                  32843
#define ID_BUTTON32844                  32844
#define ID_BUTTON32845                  32845
#define ID_BUTTON32846                  32846
#define ID_BUTTON32848                  32848
#define ID_BUTTON32849                  32849
#define ID_TOOLS_NEWDRAIN               32850
#define ID_VIEWFROMDIRECTION_GRID       32851
#define ID_VIEW_FROM_MAP_PZ             32852
#define ID_VIEWFROMDIRECTION_MAP        32853
#define ID_VIEW_FROM_MAP_NZ             32854
#define ID_BUTTON32859                  32859
#define ID_BUTTON32860                  32860
#define ID_ACCELERATOR32862             32862
#define ID_SETGRID_MODE                 32864
#define ID_SETMAP_MODE                  32865
#define ID_CANCEL_MODE                  32866
#define ID_TOOLS_ROTATE_GRID            32867
#define ID_TOOLS_ROTATEGRID             32868
#define ID_VIEW_RESETVIEWPOINT          32875
#define ID_TOOLS_NEWDOMAIN              32877
#define ID_MODE_GRID                    32879
#define ID_MODE_MAP                     32880
#define ID_EDIT_DELETE                  32881
#define IDW_CONTROLBAR_TREE             59424
#define IDW_CONTROLBAR_BOXPROPS         59425
#define IDC_VALUE_STATIC                65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        441
#define _APS_NEXT_COMMAND_VALUE         32882
#define _APS_NEXT_CONTROL_VALUE         1539
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
